
(function(){
 function $(id){return document.getElementById(id)}
 function msg(id,text,ok){var e=$(id);if(!e)return;e.textContent=text;e.className='pw-msg '+(ok?'ok':'err')}
 function off(id,v){var e=$(id);if(e)e.disabled=!!v}
 var forgot=$('forgot-form');if(forgot)forgot.addEventListener('submit',function(e){e.preventDefault();off('forgot-btn',true);fetch('https://univers.nyxia.top/api/access/password-forgot-universal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('forgot-email').value.trim(),portalHost:location.hostname})}).then(function(r){return r.json().then(function(d){return{ok:r.ok,data:d}})}).then(function(x){if(!x.ok)throw Error(x.data.error||'Envoi impossible.');msg('forgot-msg',x.data.message||'Si un compte existe pour ce courriel, un lien a été envoyé.',true)}).catch(function(e){msg('forgot-msg',e.message||'Envoi impossible.',false)}).finally(function(){off('forgot-btn',false)})});
 var reset=$('reset-form');if(reset)reset.addEventListener('submit',function(e){e.preventDefault();var p=$('reset-password').value,c=$('reset-confirm').value;if(p!==c){msg('reset-msg','Les deux mots de passe ne correspondent pas.',false);return}off('reset-btn',true);var token=new URLSearchParams(location.search).get('token')||'';fetch('/api/password/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:token,password:p,confirm:c})}).then(function(r){return r.json().then(function(d){return{ok:r.ok,data:d}})}).then(function(x){if(!x.ok)throw Error(x.data.error||'Réinitialisation impossible.');sessionStorage.removeItem('nyxia_token');sessionStorage.removeItem('nyxia_firstname');msg('reset-msg',x.data.message||'Mot de passe modifié.',true);setTimeout(function(){location.href='/login'},1200)}).catch(function(e){msg('reset-msg',e.message||'Réinitialisation impossible.',false)}).finally(function(){off('reset-btn',false)})});
 var change=$('change-form');if(change)change.addEventListener('submit',function(e){e.preventDefault();var p=$('change-password').value,c=$('change-confirm').value;if(p!==c){msg('change-msg','Les deux nouveaux mots de passe ne correspondent pas.',false);return}var token=sessionStorage.getItem('nyxia_token')||'';if(!token){location.href='/login';return}off('change-btn',true);fetch('/api/password/change',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:token,currentPassword:$('current-password').value,password:p,confirm:c})}).then(function(r){return r.json().then(function(d){return{ok:r.ok,data:d}})}).then(function(x){if(!x.ok)throw Error(x.data.error||'Changement impossible.');sessionStorage.removeItem('nyxia_token');sessionStorage.removeItem('nyxia_firstname');localStorage.removeItem('nyxia_user_context');msg('change-msg',x.data.message||'Mot de passe modifié.',true);setTimeout(function(){location.href='/login'},1200)}).catch(function(e){msg('change-msg',e.message||'Changement impossible.',false)}).finally(function(){off('change-btn',false)})});
})();

